language: node_js
node_js: stable

# assign build branches
branches:
  only:
    - sourceCode

# cache this directory
cache:
  directories:
    - node_modules
    #- themes 主题没有更改时可以缓存
# S: Build Lifecycle
before_install:
  - npm install -g hexo-cli # 安装 hexo
#  - git clone https://github.com/renyuzh/hexo-theme-next.git themes/next # 这个是博主的，主题没有更改时不用每次都下载安装一遍

install:
  - npm install # 安装 package.json 中的插件

script:
  - hexo generate

after_success:
  - git config --global user.name "fayeloh"
  - git config --global user.email "2247878900@qq.com"
  - sed -i "s/gh_token/${GH_TOKEN}/g" _config.yml #使用travisCI中配置的token替换掉_config.yml中对应的占位符
  - cat ./_config.yml
  - hexo deploy
# E: Build LifeCycle
#替换git config信息为你自己的,GH_REF的值更改为你的仓库地址.